name: deploy-auth
on:
  push:
    branches: 
      - master
    paths:
      - 'auth/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - run: cd auth && docker build -t yunoyunoyuno/auth .
      - run: docker login -u $USERNAME -p $PASSWORD
        env:
          USERNAME: ${{ DOCKER.USERNAME }}
          PASSWORD: ${{ DOCKER.PASSWORD }}
      - run: docker push yunoyunoyuno/auth
