name: deploy-manifests
on:
  push:
    branches: 
      - master
    paths:
      - 'infra/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save yn-ticketing
      - run: kubectl apply -f infra/k8s infra/k8s-prod
